### PR TITLE
Project urls

### PR DESCRIPTION
**Pull request by moshez**

### CODE REVIEW

**Comment by moshez** [comment]
Since Gather has separate pages for developer (github) docs (rtd) and a blog, I thought it would be one of the first ones I would use the project_urls feature.

Here is how it would look on pypi:
screenshot from 2018-01-24 20-21-01

**Comment by mahmoud** [comment]
Cool! Looks great!

**Comment by mahmoud** [comment]
What's this look like on legacy PyPI?

**Comment by moshez** [comment]
@mahmoud -- it ignores those fields.

**Pull request merged**
